### ISSUE TITLE
Wrong questions for Host Namespaces PSP

### ISSUE THREAD

**Issue by kravciak** [kubewarden/helm-charts#439]
Setting port value to 80 for example produces following error on policy server:
`Error(\"invalid type: string \\\"80\\\", expected a sequence\", line: 1, column: 97)")`

## Current state

Questions on kubewarden-defaults helm chart provide single input field for allow_host_ports, which generates following YAML:

![Screenshot from 2024-04-22 16-07-19](https://github.com/kubewarden/helm-charts/assets/538604/fcb49e70-782c-418c-af43-24fd5af72c05)

Yaml generated by creating policy from kubewarden-defaults helm chart:
```yaml
    settings:
      allow_host_ipc: false
      allow_host_network: false
      allow_host_pid: false
      allow_host_ports: 80,443
```

## Expected state

Policy settings expect ports to be a range, giving min & max value.

![Screenshot from 2024-04-22 16-10-20](https://github.com/kubewarden/helm-charts/assets/538604/5ed43df8-4d73-49da-b451-a61ab2df0162)

Yaml generated by creating policy from ClusterAdmissionPolicies page:

```yaml
  settings:
    allow_host_ipc: true
    allow_host_network: false
    allow_host_pid: false
    allow_host_ports:
      - min: 80
        max: 80
      - min: 8000
        max: 9000
```
